// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieTicketingApplication.Models;

public partial class Movie
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Lang { get; set; }

    public string Genre { get; set; }

    public int? Duration { get; set; }

    public string Poster { get; set; }

    public decimal? Rating { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();

    public virtual ICollection<Screen> Screens { get; set; } = new List<Screen>();

}