// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieTicketingApplication.Models;

public partial class Review
{
    public int Id { get; set; }

    public int MovieId { get; set; }

    public int UserId { get; set; }

    public decimal? Rating { get; set; }

    public string Comment { get; set; }

    public DateTime ReviewDate { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual User User { get; set; }
}