// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieTicketingApplication.Models;

public partial class Screen
{
    public int Id { get; set; }

    public int TheatreId { get; set; }

    public int? MovieId { get; set; }

    public int ScreenNumber { get; set; }

    public decimal? TicketFare { get; set; }

    public virtual Movie Movie { get; set; }

    public virtual ICollection<Show> Shows { get; set; } = new List<Show>();

    public virtual Theatre Theatre { get; set; }
}