// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieTicketingApplication.Models;

public partial class Theatre
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Location { get; set; }

    public int? Capacity { get; set; }

    public virtual ICollection<Screen> Screens { get; set; } = new List<Screen>();
}