// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MovieTicketingApplication.Models;

public partial class User
{
    public int Id { get; set; } 

    public string Fname { get; set; }

    public string Lname { get; set; }

    public string Email { get; set; }

    public string PasswordHashed { get; set; }

    public string Role { get; set; }

    public virtual ICollection<Booking> Bookings { get; set; } = new List<Booking>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}